### ISSUE TITLE
How to get detailed error messages

### ISSUE THREAD

**Issue by KDean-Dolphin** [microsoft/advanced-formula-environment#58] opened 2023-09-08 14:06 UTC
I'm getting the occasional error message saying, "Save failed: The argument is invalid or missing or has an incorrect format."

The only solution is to restart Excel. How do I get more details so that I can submit it as an issue?

**Comment by jack-williams** [comment] 2023-09-10 17:26
I'll close this one as a duplicate of #33, which tracks better error messages.

Usually, a save failure is caused by some syntax error in a formula, but there are other causes.

It is a tricky to get the exact culprit for a sync failure, but we have some ideas. I cannot make any guarantees about when we will be able to action this. I'll update the other thread if we make any changes.

**Closed as completed by jack-williams** 2023-09-10 17:26 UTC
