### ISSUE TITLE
Grid edit formula bug

### ISSUE THREAD

**Issue by ammosov** [microsoft/advanced-formula-environment#29] opened 2022-11-21 22:44 UTC
Start with: 

![image](https://user-images.githubusercontent.com/4894284/203172146-46d41ac1-b25b-4410-a2f1-4f5c4b7fb8fb.png)

Editing to - 

![image](https://user-images.githubusercontent.com/4894284/203172323-c4110a7a-4dbe-484f-82e1-ac542932348d.png)

Returning to normal edit mode 

![image](https://user-images.githubusercontent.com/4894284/203172467-687b27fe-d970-4e02-8aa6-f2416055157a.png)

Going to formula edit mode:

![image](https://user-images.githubusercontent.com/4894284/203172591-16b66c08-5fb6-4a5d-a3af-7470ba65c5f4.png)

UNDO is not available. Copy and paste restores back to original state OK. Entering the very same syntax by hand works normally.

**Comment by ammosov** [comment] 2022-11-22 00:28
I would say, the formula in the cell is expected to remain visible and editable using both method - conventional Excel and AFE grid editor.

**Comment by ammosov** [comment] 2022-11-22 00:35
UPD. I discovered by trial and error that the formula is still there in Basic Edit Mode but all spaces are passed to it too. So you can edit it but you cannot see more than a few letters at once - a function name, an argument or any other part of it on one line in AFE editor.

**Comment by jack-williams** [comment] 2022-11-22 00:35
The underlying behavior causing the problem is that we emit the formula with line-breaks. You can expand the formula bar to see the full formula:
![image](https://user-images.githubusercontent.com/4489219/203185747-e8c68aff-182a-4c9a-8a12-d3c45199f468.png)

That being said, I can see how that is still undesirable and the preferred behavior is to emit on a single line. We are tracking this in #28.

Regarding the specific issue of the Function Arguments dialog, I believe this is an issue with Excel and not AFE. If I create a multi-line formula in a workbook without AFE, such as:
```
=SUM(
1,
2
)
```
and open the insert function box, I similarly see no arguments. I would expect the Function Arguments dialog to work regardless of formula formatting.

**Comment by ammosov** [comment] 2022-11-22 00:37
Yes, this seems to be what I discovered, too. Otherwise, AFE would be my preferred edit more from now on. It would be nice if extra spaces/line breaks were trimmed for basic edit more and restored for ФАУ mode.

**Comment by jack-williams** [comment] 2022-11-22 00:39
Great, I'll close this issue as a duplicate of #28. When that is closed, I expect the behavior will be:
- Default: Break lines to fit within AFE. Save to cell on single line.
- Add option to preserve formatting between cell and AFE.

**Closed by jack-williams** 2022-11-22 00:39 UTC
